import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Activity, Flag, Headphones, Plus, Shield, Tags } from "lucide-react";
import { useEffect, useState } from "react";

export default function Admin() {
  const { user } = useAuth();
  const permitted = user?.role === "admin";
  const workspaces = trpc.admin.listWorkspaces.useQuery(undefined, { enabled: permitted });
  const health = trpc.job.health.useQuery(undefined, { enabled: permitted });
  const flags = trpc.admin.listFeatureFlags.useQuery(undefined, { enabled: permitted });
  const plans = trpc.admin.listPlans.useQuery(undefined, { enabled: permitted });
  const supportAudits = trpc.admin.recentSupportAudits.useQuery(undefined, { enabled: permitted });
  const [workspaceId, setWorkspaceId] = useState<number | undefined>();
  const [flagKey, setFlagKey] = useState("");
  const [capability, setCapability] = useState("");
  const [planSlug, setPlanSlug] = useState("");
  const [planName, setPlanName] = useState("");
  const [supportReason, setSupportReason] = useState("");
  useEffect(() => { if (!workspaceId && workspaces.data?.[0]) setWorkspaceId(workspaces.data[0].id); }, [workspaces.data, workspaceId]);
  const entitlements = trpc.admin.listEntitlements.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(permitted && workspaceId) });
  const setFlag = trpc.admin.setFeatureFlag.useMutation({ onSuccess: () => { setFlagKey(""); flags.refetch(); } });
  const setEntitlement = trpc.admin.setEntitlement.useMutation({ onSuccess: () => { setCapability(""); entitlements.refetch(); } });
  const createPlan = trpc.admin.createPlan.useMutation({ onSuccess: () => { setPlanSlug(""); setPlanName(""); plans.refetch(); } });
  const recordSupport = trpc.admin.recordSupportAccess.useMutation({ onSuccess: () => { setSupportReason(""); supportAudits.refetch(); } });

  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-6"><section className="rounded-3xl bg-[#e7dfd0] p-8"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#c65e32]">Restricted operations</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.045em]">Administration with a visible trail.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#5b6872]">Every control below is protected by the server-side administrator policy. Support activity must carry a reason and creates an audit record.</p></section>{permitted ? <>
    <section className="grid gap-4 md:grid-cols-3"><Card><CardHeader><Shield className="h-5 w-5 text-[#516f5e]" /><CardTitle className="mt-4 text-lg">Tenant scope</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold tracking-tight">{workspaces.data?.length ?? "—"}</p><p className="mt-1 text-sm text-muted-foreground">visible workspaces</p></CardContent></Card><Card><CardHeader><Activity className="h-5 w-5 text-[#c65e32]" /><CardTitle className="mt-4 text-lg">Queue health</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold tracking-tight">{health.data?.counts.queued ?? 0}</p><p className="mt-1 text-sm text-muted-foreground">queued jobs · {health.data?.counts.running ?? 0} processing</p></CardContent></Card><Card><CardHeader><Flag className="h-5 w-5 text-[#516f5e]" /><CardTitle className="mt-4 text-lg">Feature flags</CardTitle></CardHeader><CardContent><p className="text-3xl font-semibold tracking-tight">{flags.data?.length ?? "—"}</p><p className="mt-1 text-sm text-muted-foreground">scoped flag records</p></CardContent></Card></section>
    <section className="grid gap-5 lg:grid-cols-[0.85fr_1.15fr]"><Card className="border-border bg-white"><CardHeader><CardTitle>Tenant management</CardTitle><CardDescription>Select a workspace to inspect entitlement state or document a support action.</CardDescription></CardHeader><CardContent className="space-y-3"><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={workspaceId ?? ""} onChange={event => setWorkspaceId(Number(event.target.value))}><option value="">Select workspace</option>{workspaces.data?.map(workspace => <option key={workspace.id} value={workspace.id}>{workspace.name} · {workspace.kind}</option>)}</select><div className="max-h-48 space-y-2 overflow-auto">{workspaces.data?.map(workspace => <button key={workspace.id} onClick={() => setWorkspaceId(workspace.id)} className={`w-full rounded-xl border p-3 text-left transition ${workspace.id === workspaceId ? "border-[#516f5e] bg-[#e4eee6]" : "border-border hover:bg-muted/30"}`}><p className="text-sm font-medium">{workspace.name}</p><p className="mt-1 text-xs text-muted-foreground">{workspace.slug} · {workspace.isArchived ? "archived" : "active"}</p></button>)}</div></CardContent></Card><Card className="border-border bg-white"><CardHeader><CardTitle>Commercial access controls</CardTitle><CardDescription>These records establish server-enforced capability foundations. They do not collect or process payment data.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Input value={capability} onChange={event => setCapability(event.target.value)} placeholder="Capability, e.g. studio.delivery" /><Button disabled={!workspaceId || !capability || setEntitlement.isPending} onClick={() => workspaceId && setEntitlement.mutate({ workspaceId, capability, isEnabled: true })} className="bg-[#516f5e] hover:bg-[#405c4c]">Enable</Button></div><div className="space-y-2">{entitlements.data?.map(entitlement => <div key={entitlement.id} className="flex items-center justify-between rounded-xl border border-border p-3"><span className="text-sm font-medium">{entitlement.capability}</span><span className={`rounded-full px-2.5 py-1 text-xs ${entitlement.isEnabled ? "bg-[#e4eee6] text-[#405c4c]" : "bg-muted text-muted-foreground"}`}>{entitlement.isEnabled ? "Enabled" : "Disabled"}</span></div>)}{workspaceId && entitlements.data?.length === 0 ? <p className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">No explicit entitlement records yet.</p> : null}</div></CardContent></Card></section>
    <section className="grid gap-5 lg:grid-cols-2"><Card className="border-border bg-white"><CardHeader><CardTitle className="flex items-center gap-2"><Flag className="h-5 w-5 text-[#c65e32]" />Scoped feature flags</CardTitle><CardDescription>Flags can be globally scoped or attached to the currently selected workspace. Expiry/rollout policy remains documented work.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input value={flagKey} onChange={event => setFlagKey(event.target.value)} placeholder="Feature key" /><Button disabled={!flagKey || setFlag.isPending} onClick={() => setFlag.mutate({ key: flagKey, workspaceId, isEnabled: true })} className="bg-[#17202b] hover:bg-[#2a3746]">Set</Button></div>{flags.data?.map(flag => <div key={flag.id} className="flex items-center justify-between rounded-xl border border-border p-3"><div><p className="text-sm font-medium">{flag.key}</p><p className="mt-1 text-xs text-muted-foreground">{flag.workspaceId ? `Workspace #${flag.workspaceId}` : "Global scope"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs ${flag.isEnabled ? "bg-[#e4eee6] text-[#405c4c]" : "bg-muted text-muted-foreground"}`}>{flag.isEnabled ? "On" : "Off"}</span></div>)}</CardContent></Card><Card className="border-border bg-white"><CardHeader><CardTitle className="flex items-center gap-2"><Tags className="h-5 w-5 text-[#516f5e]" />Plan records</CardTitle><CardDescription>Create controlled packaging records before a payment provider is selected.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-2"><Input value={planSlug} onChange={event => setPlanSlug(event.target.value)} placeholder="plan-slug" /><Input value={planName} onChange={event => setPlanName(event.target.value)} placeholder="Plan name" /></div><Button disabled={!planSlug || !planName || createPlan.isPending} onClick={() => createPlan.mutate({ slug: planSlug, name: planName })} className="bg-[#516f5e] hover:bg-[#405c4c]"><Plus className="mr-1 h-4 w-4" />Create plan</Button><div className="space-y-2">{plans.data?.map(plan => <div key={plan.id} className="rounded-xl border border-border p-3"><p className="text-sm font-medium">{plan.name}</p><p className="mt-1 text-xs text-muted-foreground">{plan.slug} · {plan.isActive ? "active" : "inactive"}</p></div>)}</div></CardContent></Card></section>
    <section className="grid gap-5 lg:grid-cols-2"><Card className="border-[#d9ae72] bg-[#fff7e9]"><CardHeader><CardTitle className="flex items-center gap-2"><Headphones className="h-5 w-5 text-[#c65e32]" />Audited support access</CardTitle><CardDescription>Use only for an explicit tenant support need. This records the reason; it does not impersonate a member or bypass tenant authorization.</CardDescription></CardHeader><CardContent className="space-y-3"><Input value={supportReason} onChange={event => setSupportReason(event.target.value)} placeholder="Reason for support access (10+ characters)" /><Button disabled={!workspaceId || supportReason.trim().length < 10 || recordSupport.isPending} onClick={() => workspaceId && recordSupport.mutate({ workspaceId, reason: supportReason })} className="bg-[#c65e32] hover:bg-[#ad4e29]">Record support access</Button>{recordSupport.isSuccess ? <p className="text-sm text-[#405c4c]">Support record created.</p> : null}</CardContent></Card><Card className="border-border bg-white"><CardHeader><CardTitle>Recent support audit records</CardTitle><CardDescription>Audits are append-only action records available to restricted operations.</CardDescription></CardHeader><CardContent className="space-y-2">{supportAudits.data?.map(audit => <div key={audit.id} className="rounded-xl border border-border p-3"><p className="text-sm font-medium">{audit.action}</p><p className="mt-1 text-xs text-muted-foreground">Workspace {audit.workspaceId ?? "platform"} · {new Date(audit.createdAt).toLocaleString()}</p></div>)}{supportAudits.data?.length === 0 ? <p className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">No support-access records exist yet.</p> : null}</CardContent></Card></section>
  </> : <Card className="border-destructive/30 bg-destructive/5"><CardContent className="p-6"><p className="font-medium text-destructive">Administrator permission is required.</p><p className="mt-2 text-sm text-muted-foreground">The route shell may be visible, but operational actions remain server-restricted and audit-visible.</p></CardContent></Card>}</div></DashboardLayout>;
}
