import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { ArrowRight, ArrowUpRight, Menu, MoveRight } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useState } from "react";
import { Link } from "wouter";

export default function Home() {
  const [email, setEmail] = useState("");
  const leadCapture = trpc.lead.capture.useMutation();
  return (
    <main className="evercrafted-surface min-h-screen overflow-hidden">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-12" aria-label="Evercrafted navigation"><Link href="/" className="font-editorial text-2xl tracking-[-0.04em]">Evercrafted</Link><div className="hidden items-center gap-7 text-sm text-stone-600 md:flex"><a href="#collections">Collections</a><a href="#journal">Journal</a><a href="#about">About</a><a href="#contact">Contact</a><Link href="/client">Client</Link></div><div className="flex items-center gap-3"><Button variant="outline" onClick={startLogin} className="hidden rounded-full border-stone-300 bg-transparent sm:inline-flex">Account</Button><Menu className="h-5 w-5 md:hidden" /></div></nav>
      <section className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-12 sm:px-8 lg:grid-cols-[.86fr_1.14fr] lg:px-12 lg:pb-28 lg:pt-20"><div className="flex flex-col justify-between py-3"><div><p className="text-xs uppercase tracking-[.2em] text-stone-500">Evercrafted · 01</p><h1 className="font-editorial mt-8 max-w-xl text-6xl leading-[.88] tracking-[-.055em] text-stone-900 sm:text-7xl">Made for the life around it.</h1><p className="mt-8 max-w-md text-base leading-7 text-stone-600">Considered objects, enduring materials, and a more deliberate rhythm for the spaces people return to every day.</p></div><a href="#collections" className="mt-12 inline-flex items-center gap-2 text-sm font-medium text-stone-800">Explore the collection <MoveRight className="h-4 w-4" /></a></div><div className="relative min-h-[460px] overflow-hidden rounded-[2.2rem] bg-stone-200"><img src="/manus-storage/evercrafted-neutral-interior_7597196d.jpg" alt="Calm neutral interior with architectural detailing" className="h-full w-full object-cover" /><div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/55 to-transparent p-7 text-white"><p className="text-xs uppercase tracking-[.18em] text-white/70">A quieter kind of utility</p><p className="font-editorial mt-2 max-w-md text-2xl leading-tight">Objects that earn their place over time.</p></div></div></section>
      <section id="collections" className="border-y border-stone-300/70 bg-[#ece8df] px-5 py-20 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs uppercase tracking-[.2em] text-stone-500">Collections</p><h2 className="font-editorial mt-4 text-5xl leading-none tracking-[-.045em] text-stone-900">Curated by material, not momentum.</h2></div><p className="max-w-xl self-end text-base leading-7 text-stone-600">Explore Evercrafted through material stories, considered pairings, and pieces selected to work together without asking for attention.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3"><article className="overflow-hidden rounded-2xl bg-[#f8f6f1]"><img src="/manus-storage/evercrafted-stone-vessel_520e889f.png" alt="Stone vessel on a textured surface" className="h-64 w-full object-cover" /><div className="p-5"><p className="text-xs uppercase tracking-[.16em] text-stone-500">Material study</p><h3 className="font-editorial mt-3 text-3xl">Stone</h3></div></article><article className="rounded-2xl bg-stone-900 p-6 text-stone-100"><p className="text-xs uppercase tracking-[.16em] text-stone-400">Room study</p><h3 className="font-editorial mt-16 text-4xl leading-none">Objects with a settled point of view.</h3><p className="mt-8 text-sm leading-6 text-stone-300">Collection details will appear here from verified catalog data.</p></article><article className="overflow-hidden rounded-2xl bg-[#f8f6f1]"><img src="/manus-storage/evercrafted-studio-workspace_9400a257.jpg" alt="Minimal studio workspace" className="h-64 w-full object-cover" /><div className="p-5"><p className="text-xs uppercase tracking-[.16em] text-stone-500">Spatial study</p><h3 className="font-editorial mt-3 text-3xl">Work</h3></div></article></div></div></section>
      <section id="journal" className="mx-auto grid max-w-7xl gap-10 px-5 py-24 sm:px-8 lg:grid-cols-2 lg:px-12"><div className="rounded-[2rem] bg-stone-900 p-8 text-stone-100 sm:p-12"><p className="text-xs uppercase tracking-[.2em] text-stone-400">Journal</p><h2 className="font-editorial mt-10 text-5xl leading-[.92] tracking-[-.045em]">The record of a room.</h2><p className="mt-7 max-w-md text-sm leading-7 text-stone-300">Notes on material, process, spaces, and the work that gives lasting objects their point of view.</p><a href="#contact" className="mt-10 inline-flex items-center gap-2 text-sm font-medium">Read the journal <ArrowUpRight className="h-4 w-4" /></a></div><div id="about" className="flex flex-col justify-center"><p className="text-xs uppercase tracking-[.2em] text-stone-500">Evercrafted</p><h2 className="font-editorial mt-5 max-w-lg text-5xl leading-[.92] tracking-[-.045em] text-stone-900">Built around the long view.</h2><p className="mt-7 max-w-lg text-base leading-7 text-stone-600">We value clarity over excess, care over novelty, and work that feels more settled over time.</p><Link href="/client" className="mt-10 inline-flex items-center gap-2 text-sm font-medium text-stone-800">Looking for your client workspace? <ArrowRight className="h-4 w-4" /></Link></div></section>
      <section id="contact" className="border-t border-stone-300 bg-[#e4ded2] px-5 py-18 sm:px-8 lg:px-12"><div className="mx-auto grid max-w-7xl gap-8 py-16 md:grid-cols-[1fr_auto] md:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-stone-500">Contact</p><h2 className="font-editorial mt-4 text-5xl tracking-[-.045em] text-stone-900">Begin with what matters.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-stone-600">For collection questions, sourcing inquiries, or a more considered starting point, we would be glad to hear from you.</p></div><form onSubmit={event => { event.preventDefault(); if (email) leadCapture.mutate({ email, interest: "evercrafted_inquiry" }); }} className="flex w-full max-w-md flex-col gap-2 sm:flex-row"><input type="email" required value={email} onChange={event => setEmail(event.target.value)} placeholder="Email address" className="h-11 flex-1 rounded-full border border-stone-300 bg-[#f8f6f1] px-4 text-sm outline-none ring-stone-700 focus:ring-2" /><Button type="submit" disabled={leadCapture.isPending} className="rounded-full bg-stone-900 px-5 text-white hover:bg-stone-700">{leadCapture.isSuccess ? "Received" : leadCapture.isPending ? "Sending…" : "Send inquiry"}</Button></form>{leadCapture.error ? <p className="md:col-span-2 text-sm text-destructive">We could not save that inquiry. Please try again.</p> : null}</div></section>
    </main>
  );
}
