import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { BellRing, CheckCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function Notifications() {
  const notifications = trpc.notification.listMine.useQuery();
  const markRead = trpc.notification.markRead.useMutation({ onSuccess: () => notifications.refetch() });
  return <DashboardLayout><div className="mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#c65e32]">Workspace updates</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.045em]">Notifications in context.</h1><p className="mt-2 text-sm text-muted-foreground">Workflow and job updates will be delivered according to the same workspace permission rules as the action that created them.</p><div className="mt-7 space-y-3">{notifications.isLoading ? <p className="text-sm text-muted-foreground">Loading your notifications…</p> : null}{notifications.data?.map(notification => <article key={notification.id} className={`rounded-2xl border p-5 shadow-sm ${notification.readAt ? "border-border bg-white" : "border-[#d9ae72] bg-[#fff7e9]"}`}><div className="flex items-start justify-between gap-4"><div><p className="font-medium">{notification.title}</p>{notification.body ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{notification.body}</p> : null}<p className="mt-3 text-xs text-muted-foreground">{new Date(notification.createdAt).toLocaleString()}</p></div>{!notification.readAt ? <Button variant="outline" size="sm" disabled={markRead.isPending} onClick={() => markRead.mutate({ notificationId: notification.id })}><CheckCheck className="mr-1 h-4 w-4" />Read</Button> : null}</div></article>)}{!notifications.isLoading && notifications.data?.length === 0 ? <div className="rounded-3xl border border-dashed border-border p-10 text-center"><BellRing className="mx-auto h-8 w-8 text-[#c65e32]" /><h2 className="mt-4 text-lg font-semibold">You are all caught up.</h2><p className="mt-2 text-sm text-muted-foreground">Notifications will appear here as authorized work moves through its lifecycle.</p></div> : null}</div></div></DashboardLayout>;
}
