import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { BellRing, CheckCheck, ExternalLink, Loader2, RefreshCw } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useLocation } from "wouter";

export default function Notifications() {
  const [, setLocation] = useLocation();
  const notifications = trpc.notification.listMine.useQuery();
  const preferenceStatus = trpc.notification.preferenceStatus.useQuery();
  const markRead = trpc.notification.markRead.useMutation({ onSuccess: () => notifications.refetch() });
  const openNotification = async (notification: { id: number; actionUrl: string | null }) => {
    await markRead.mutateAsync({ notificationId: notification.id });
    if (notification.actionUrl?.startsWith("/")) setLocation(notification.actionUrl);
  };
  return <DashboardLayout><main id="main-content" className="mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#c65e32]">Workspace updates</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.045em]">Notifications in context.</h1><p className="mt-2 text-sm text-muted-foreground">Workflow and job updates respect the same workspace permission rules as the action that created them.</p>
    <section aria-label="Delivery preferences" className="mt-5 rounded-2xl border border-border bg-white p-4 text-sm text-muted-foreground"><p><span className="font-medium text-foreground">In-app delivery:</span> {preferenceStatus.data?.inAppEnabled ? "enabled" : preferenceStatus.data ? "paused" : "loading"}. {preferenceStatus.data?.emailEnabled ? "Email delivery is enabled for future provider routing." : "Email delivery remains disabled until a provider is configured."}</p></section>
    <div className="mt-7 space-y-3">{notifications.isLoading ? <p className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />Loading your notifications…</p> : null}{notifications.error ? <div role="alert" className="rounded-2xl border border-destructive/30 bg-destructive/5 p-5"><p className="text-sm font-medium text-destructive">We could not load your notifications.</p><Button className="mt-3" variant="outline" size="sm" onClick={() => notifications.refetch()}><RefreshCw className="mr-1 h-4 w-4" />Try again</Button></div> : null}{notifications.data?.map(notification => <article key={notification.id} className={`rounded-2xl border p-5 shadow-sm ${notification.readAt ? "border-border bg-white" : "border-[#d9ae72] bg-[#fff7e9]"}`}><div className="flex items-start justify-between gap-4"><div><p className="font-medium">{notification.title}</p>{notification.body ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{notification.body}</p> : null}<p className="mt-3 text-xs text-muted-foreground">{new Date(notification.createdAt).toLocaleString()}</p></div><div className="flex shrink-0 gap-2">{notification.actionUrl ? <Button variant="outline" size="sm" disabled={markRead.isPending} onClick={() => openNotification(notification)}><ExternalLink className="mr-1 h-4 w-4" />Open</Button> : null}{!notification.readAt ? <Button variant="outline" size="sm" disabled={markRead.isPending} onClick={() => markRead.mutate({ notificationId: notification.id })}><CheckCheck className="mr-1 h-4 w-4" />Read</Button> : null}</div></div></article>)}{!notifications.isLoading && !notifications.error && notifications.data?.length === 0 ? <div className="rounded-3xl border border-dashed border-border p-10 text-center"><BellRing className="mx-auto h-8 w-8 text-[#c65e32]" /><h2 className="mt-4 text-lg font-semibold">You are all caught up.</h2><p className="mt-2 text-sm text-muted-foreground">Notifications will appear here as authorized work moves through its lifecycle.</p></div> : null}</div></main></DashboardLayout>;
}
