import SkipLink from "@/components/SkipLink";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { Check } from "lucide-react";
import { Link } from "wouter";

const tiers = [
  { name: "Foundation", intent: "Personal and early team workspaces", detail: "Start with a private space and the shared project operating model.", features: ["Personal workspace auto-provisioning", "Projects and scoped membership", "Moodoor Studio foundation", "In-app operational context"] },
  { name: "Studio", intent: "Creative teams moving client work", detail: "Add governed creative workflow, collaborative delivery, and expanding team controls.", features: ["Asset metadata and version records", "Review and approval workflow", "Workspace invitations and roles", "Durable job and notification foundation"], featured: true },
  { name: "Scale", intent: "Organizations with governed operations", detail: "Extend the same engine with entitlements, support controls, integrations, and observability.", features: ["Plan and entitlement foundations", "Audited support access", "Platform operations dashboard", "Provider-reviewed worker adapters"] },
];

export default function Pricing() {
  return <><SkipLink /><main id="main-content" className="min-h-screen bg-[#f7f5ef] text-[#17202b]"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-12" aria-label="Evercrafted pricing navigation"><Link href="/" className="flex items-center gap-2.5 font-semibold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#17202b] text-sm text-[#f7f5ef]">E</span>Evercrafted</Link><Link href="/product" className="text-sm hover:text-[#516f5e]">Product</Link></nav><section className="mx-auto max-w-7xl px-5 pb-20 pt-16 sm:px-8 lg:px-12"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#c65e32]">Pricing direction</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.06em] sm:text-6xl">Scale the system, not the complexity.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#56636d]">These are product packaging directions, not payment offers. Final prices, billing terms, and payment-provider configuration will be added only after the commercial model is approved.</p><div className="mt-14 grid gap-5 lg:grid-cols-3">{tiers.map(tier => <article key={tier.name} className={`rounded-3xl border p-7 shadow-sm ${tier.featured ? "border-[#516f5e] bg-[#516f5e] text-[#f7f5ef]" : "border-[#17202b]/10 bg-white"}`}><p className={`text-xs font-semibold uppercase tracking-[0.15em] ${tier.featured ? "text-[#f3d5aa]" : "text-[#c65e32]"}`}>{tier.intent}</p><h2 className="mt-5 text-3xl font-semibold tracking-tight">{tier.name}</h2><p className={`mt-3 min-h-20 text-sm leading-6 ${tier.featured ? "text-[#e8eee9]/80" : "text-[#5b6872]"}`}>{tier.detail}</p><ul className="mt-7 space-y-3">{tier.features.map(feature => <li key={feature} className={`flex gap-2 text-sm ${tier.featured ? "text-[#f7f5ef]" : "text-[#43515d]"}`}><Check className={`h-4 w-4 shrink-0 ${tier.featured ? "text-[#f3d5aa]" : "text-[#516f5e]"}`} />{feature}</li>)}</ul><Button onClick={startLogin} variant={tier.featured ? "secondary" : "outline"} className={`mt-9 w-full rounded-full ${tier.featured ? "bg-[#f3d5aa] text-[#2b241b] hover:bg-[#f8dfbc]" : ""}`}>Create a workspace</Button></article>)}</div></section></main></>;
}
