import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Gauge, KeyRound, Link2, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";

export default function Settings() {
  const { isAuthenticated } = useAuth();
  const spaces = trpc.workspace.listMine.useQuery(undefined, { enabled: isAuthenticated });
  const [workspaceId, setWorkspaceId] = useState<number | undefined>();
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<"admin" | "member" | "viewer" | "client">("member");
  useEffect(() => { if (!workspaceId && spaces.data?.[0]) setWorkspaceId(spaces.data[0].id); }, [spaces.data, workspaceId]);
  const invitations = trpc.workspace.listInvitations.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const entitlements = trpc.workspace.entitlements.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const commercial = trpc.workspace.commercialOverview.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const invite = trpc.workspace.invite.useMutation({ onSuccess: () => { setEmail(""); invitations.refetch(); } });

  return <DashboardLayout><div className="mx-auto max-w-4xl"><h1 className="text-3xl font-semibold tracking-[-0.045em]">Workspace settings</h1><p className="mt-2 text-sm text-muted-foreground">Membership, invitations, integrations, and future delivery preferences use the same workspace policy model.</p>
    <Card className="mt-6 border-border bg-white shadow-sm"><CardHeader><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e4eee6] text-[#516f5e]"><UsersRound className="h-4 w-4" /></span><div><CardTitle>Invite collaborators</CardTitle><CardDescription>Only workspace owners and administrators can create role-scoped, seven-day invitation codes.</CardDescription></div></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_1.2fr_0.8fr_auto]"><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={workspaceId ?? ""} onChange={event => setWorkspaceId(Number(event.target.value))}><option value="">Workspace</option>{spaces.data?.map(space => <option key={space.id} value={space.id}>{space.name}</option>)}</select><Input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="collaborator@company.com" /><select className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={role} onChange={event => setRole(event.target.value as typeof role)}><option value="admin">Admin</option><option value="member">Member</option><option value="viewer">Viewer</option><option value="client">Client</option></select><Button disabled={!workspaceId || !email || invite.isPending} onClick={() => workspaceId && invite.mutate({ workspaceId, email, role })} className="bg-[#516f5e] hover:bg-[#405c4c]">{invite.isPending ? "Creating…" : "Create invite"}</Button></div>{invite.data ? <div className="rounded-xl bg-[#fff7e9] p-4"><p className="flex items-center gap-2 text-sm font-medium"><Link2 className="h-4 w-4 text-[#c65e32]" /> Invitation code created</p><p className="mt-2 break-all rounded-lg bg-white p-2 font-mono text-xs text-muted-foreground">{invite.data.token}</p><p className="mt-2 text-xs text-muted-foreground">Share this code securely. The future email provider adapter will deliver it automatically after configuration and review.</p></div> : null}{invite.error ? <p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">You may not have permission to invite users to this workspace.</p> : null}</CardContent></Card>
    <div className="mt-6 grid gap-5 md:grid-cols-[1.3fr_0.7fr]"><Card><CardHeader><CardTitle>Invitation history</CardTitle><CardDescription>Codes are scoped to the selected workspace and retained as auditable invitation records.</CardDescription></CardHeader><CardContent className="space-y-2">{invitations.isLoading ? <p className="text-sm text-muted-foreground">Loading invitation records…</p> : null}{invitations.data?.map(invitation => <div key={invitation.id} className="flex items-center justify-between rounded-xl border border-border p-3"><div><p className="text-sm font-medium">{invitation.email}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{invitation.role} · expires {new Date(invitation.expiresAt).toLocaleDateString()}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${invitation.acceptedAt ? "bg-[#e4eee6] text-[#405c4c]" : invitation.revokedAt ? "bg-muted text-muted-foreground" : "bg-[#fff0d7] text-[#a9522d]"}`}>{invitation.acceptedAt ? "Accepted" : invitation.revokedAt ? "Revoked" : "Pending"}</span></div>)}{workspaceId && !invitations.isLoading && invitations.data?.length === 0 ? <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">No invitation records exist in this workspace yet.</p> : null}</CardContent></Card><Card><CardHeader><KeyRound className="h-6 w-6 text-[#c65e32]" /><CardTitle className="mt-5">Workspace capabilities</CardTitle><CardDescription>Explicit capability records are enforced server-side; unlisted capabilities follow the current default workspace policy.</CardDescription></CardHeader><CardContent className="space-y-2">{entitlements.isLoading ? <p className="text-sm text-muted-foreground">Loading capabilities…</p> : null}{entitlements.data?.map(entitlement => <div key={entitlement.id} className="flex items-center justify-between rounded-xl border border-border p-3"><span className="text-sm font-medium">{entitlement.capability}</span><span className={`rounded-full px-2.5 py-1 text-xs ${entitlement.isEnabled ? "bg-[#e4eee6] text-[#405c4c]" : "bg-muted text-muted-foreground"}`}>{entitlement.isEnabled ? "Enabled" : "Disabled"}</span></div>)}{workspaceId && !entitlements.isLoading && entitlements.data?.length === 0 ? <p className="text-sm leading-6 text-muted-foreground">No explicit capability records apply yet. Your workspace follows the current default policy.</p> : null}</CardContent></Card></div>
    <Card className="mt-6"><CardHeader><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e4eee6] text-[#516f5e]"><Gauge className="h-4 w-4" /></span><div><CardTitle>Plan and usage</CardTitle><CardDescription>Current workspace packaging and current-period usage records are visible to members. Billing is not configured in this workspace.</CardDescription></div></div></CardHeader><CardContent className="grid gap-5 md:grid-cols-[0.85fr_1.15fr]">{commercial.isLoading ? <p className="text-sm text-muted-foreground">Loading plan and usage state…</p> : null}{commercial.isError ? <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive"><p>Plan and usage state could not be loaded.</p><Button className="mt-3" variant="outline" onClick={() => commercial.refetch()}>Retry plan state</Button></div> : null}{commercial.data ? <><div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Subscription lifecycle</p>{commercial.data.subscriptions.map(subscription => <div key={subscription.id} className="rounded-xl border border-border p-3"><p className="text-sm font-medium">{subscription.planName}</p><p className="mt-1 text-xs text-muted-foreground">{subscription.status.replace("_", " ")} · started {new Date(subscription.currentPeriodStart).toLocaleDateString()}{subscription.currentPeriodEnd ? ` · ends ${new Date(subscription.currentPeriodEnd).toLocaleDateString()}` : ""}</p></div>)}{commercial.data.subscriptions.length === 0 ? <p className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">No subscription lifecycle record has been assigned to this workspace yet.</p> : null}<p className="text-xs text-muted-foreground">Billing provider: {commercial.data.billingProvider}. Contact your workspace administrator for commercial changes.</p></div><div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">Current-period usage</p>{commercial.data.usage.map(record => <div key={record.id} className="flex items-center justify-between rounded-xl border border-border p-3"><div><p className="text-sm font-medium">{record.metric}</p><p className="mt-1 text-xs text-muted-foreground">Period ends {new Date(record.periodEnd).toLocaleDateString()}</p></div><p className="text-xl font-semibold">{record.quantity}</p></div>)}{commercial.data.usage.length === 0 ? <p className="rounded-xl border border-dashed p-3 text-sm text-muted-foreground">No current-period usage has been recorded.</p> : null}</div></> : null}</CardContent></Card>
  </div></DashboardLayout>;
}
