import DashboardLayout from "@/components/DashboardLayout";
import StudioAssetVersionHistory from "@/components/StudioAssetVersionHistory";
import StudioProjectCreation from "@/components/StudioProjectCreation";
import StudioPublishingHandoff from "@/components/StudioPublishingHandoff";
import StudioWorkflowFeedback from "@/components/StudioWorkflowFeedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, FileUp, PackageCheck, Send, ThumbsDown } from "lucide-react";
import { ChangeEvent, useEffect, useMemo, useState } from "react";

const stages = ["draft", "active", "in_review", "approved", "delivered"] as const;

function readAsBase64(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("The selected file could not be read."));
    reader.onload = () => resolve(String(reader.result).split(",")[1] ?? "");
    reader.readAsDataURL(file);
  });
}

export default function Studio() {
  const { isAuthenticated } = useAuth();
  const [workspaceId, setWorkspaceId] = useState<number>();
  const [projectId, setProjectId] = useState<number>();
  const [reviewNote, setReviewNote] = useState("");
  const [reviewerUserId, setReviewerUserId] = useState<number>();
  const [destinationType, setDestinationType] = useState("secure_link");
  const [destinationRef, setDestinationRef] = useState("");
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [workflowNotice, setWorkflowNotice] = useState<string | null>(null);

  const spaces = trpc.workspace.listMine.useQuery(undefined, { enabled: isAuthenticated });
  const projects = trpc.project.list.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const members = trpc.workspace.listMembers.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const assets = trpc.asset.list.useQuery({ workspaceId: workspaceId ?? 0, projectId }, { enabled: Boolean(workspaceId) });
  const reviews = trpc.studio.listReviews.useQuery({ workspaceId: workspaceId ?? 0, projectId: projectId ?? 0 }, { enabled: Boolean(workspaceId && projectId) });
  const deliveries = trpc.studio.listDeliveries.useQuery({ workspaceId: workspaceId ?? 0, projectId: projectId ?? 0 }, { enabled: Boolean(workspaceId && projectId) });

  useEffect(() => { if (!workspaceId && spaces.data?.[0]) setWorkspaceId(spaces.data[0].id); }, [spaces.data, workspaceId]);
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(projects.data[0].id); }, [projects.data, projectId]);
  const selectedProject = useMemo(() => projects.data?.find(project => project.id === projectId), [projects.data, projectId]);

  const transition = trpc.studio.transitionProject.useMutation({ onSuccess: () => { projects.refetch(); setWorkflowNotice("Project stage updated."); } });
  const upload = trpc.asset.uploadBase64.useMutation({ onSuccess: () => { setUploadError(null); assets.refetch(); setWorkflowNotice("Asset uploaded."); } });
  const downloadUrl = trpc.asset.downloadUrl.useMutation({ onSuccess: result => window.open(result.url, "_blank", "noopener,noreferrer") });
  const requestReview = trpc.studio.requestReview.useMutation({ onSuccess: () => { setReviewNote(""); reviews.refetch(); setWorkflowNotice("Review request created."); } });
  const respond = trpc.studio.respondToReview.useMutation({ onSuccess: () => { reviews.refetch(); setWorkflowNotice("Review response recorded."); } });
  const createDelivery = trpc.studio.createDelivery.useMutation({ onSuccess: () => { setDestinationRef(""); deliveries.refetch(); setWorkflowNotice("Delivery record created."); } });
  const readyDelivery = trpc.studio.markDeliveryReady.useMutation({ onSuccess: () => { deliveries.refetch(); setWorkflowNotice("Delivery marked ready."); } });

  const onAssetFile = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file || !workspaceId) return;
    if (file.size > 5 * 1024 * 1024) { setUploadError("Choose a file smaller than 5 MiB."); return; }
    try { upload.mutate({ workspaceId, projectId, name: file.name, mediaType: file.type || "application/octet-stream", base64: await readAsBase64(file) }); }
    catch (error) { setUploadError(error instanceof Error ? error.message : "The file could not be prepared for upload."); }
  };

  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-7">
    <section className="overflow-hidden rounded-[2rem] bg-[#516f5e] p-7 text-[#f7f5ef] sm:p-10"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#f3d5aa]">Moodoor Studio</p><div className="mt-4 grid gap-7 lg:grid-cols-[1.15fr_0.85fr]"><div><h1 className="text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">The creative room is part of the operating system.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#e8eee9]/80">Studio uses the same workspace, membership, project, review, delivery, asset, and audit controls as the shared Ever Engine.</p></div><div className="rounded-3xl border border-white/15 bg-[#17202b]/25 p-5"><p className="text-sm font-medium">Controlled delivery path</p><p className="mt-2 text-sm leading-6 text-[#e8eee9]/75">External publishing remains disconnected until a reviewed provider adapter is configured. Delivery preparation and handoff are nevertheless traceable.</p></div></div></section>

    <Card className="border-border bg-white/80"><CardContent className="grid gap-4 p-5 md:grid-cols-2"><label className="space-y-2" htmlFor="studio-workspace"><span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Workspace</span><select id="studio-workspace" className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={workspaceId ?? ""} onChange={event => { setWorkspaceId(Number(event.target.value)); setProjectId(undefined); }}><option value="">Select a workspace</option>{spaces.data?.map(space => <option key={space.id} value={space.id}>{space.name} · {space.role}</option>)}</select></label><label className="space-y-2" htmlFor="studio-project"><span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Studio project</span><select id="studio-project" className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={projectId ?? ""} onChange={event => setProjectId(Number(event.target.value))}><option value="">Choose a project</option>{projects.data?.map(project => <option key={project.id} value={project.id}>{project.name} · {project.status}</option>)}</select></label></CardContent></Card>

    <StudioWorkflowFeedback notice={workflowNotice} queries={[{ label: "workspaces", error: spaces.error, retry: spaces.refetch }, { label: "projects", error: projects.error, retry: projects.refetch }, { label: "members", error: members.error, retry: members.refetch }, { label: "assets", error: assets.error, retry: assets.refetch }, { label: "reviews", error: reviews.error, retry: reviews.refetch }, { label: "deliveries", error: deliveries.error, retry: deliveries.refetch }]} mutations={[{ label: "Project stage update", error: transition.error }, { label: "Asset upload", error: upload.error }, { label: "Review request", error: requestReview.error }, { label: "Review response", error: respond.error }, { label: "Delivery creation", error: createDelivery.error }, { label: "Delivery readiness update", error: readyDelivery.error }]} />
    {workspaceId ? <StudioProjectCreation workspaceId={workspaceId} onCreated={setProjectId} /> : null}

    {selectedProject ? <><section className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><Card className="border-[#d9ae72] bg-[#fff7e9]"><CardHeader><CardTitle>{selectedProject.name}</CardTitle><CardDescription>{selectedProject.description || "Studio project with an auditable workflow history."}</CardDescription></CardHeader><CardContent><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#c65e32]">Current stage</p><div className="mt-4 space-y-2">{stages.map(stage => <button key={stage} disabled={transition.isPending || selectedProject.status === stage} onClick={() => workspaceId && transition.mutate({ workspaceId, projectId: selectedProject.id, toStatus: stage })} className={`flex w-full items-center justify-between rounded-xl border px-3 py-2 text-left text-sm capitalize transition ${selectedProject.status === stage ? "border-[#516f5e] bg-[#e4eee6] font-medium text-[#405c4c]" : "border-[#d9ae72]/50 bg-white/60 hover:bg-white"}`}><span>{stage.replace("_", " ")}</span>{selectedProject.status === stage ? <CheckCircle2 className="h-4 w-4" /> : <ArrowRight className="h-4 w-4 text-muted-foreground" />}</button>)}</div></CardContent></Card>
      <Card className="border-border bg-white shadow-sm"><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle>Project assets</CardTitle><CardDescription className="mt-1">A maximum of 5 MiB per file applies to this governed upload path.</CardDescription></div><label className="inline-flex h-9 cursor-pointer items-center rounded-lg bg-[#17202b] px-3 text-sm font-medium text-white transition hover:bg-[#2a3746]"><FileUp className="mr-1 h-4 w-4" />{upload.isPending ? "Uploading…" : "Upload asset"}<Input type="file" className="sr-only" onChange={onAssetFile} disabled={upload.isPending} /></label></div></CardHeader><CardContent className="space-y-3">{uploadError ? <p role="alert" className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{uploadError}</p> : null}{assets.isLoading ? <p className="text-sm text-muted-foreground">Loading project assets…</p> : null}{assets.data?.map(asset => <div key={asset.id} className="flex items-center justify-between rounded-xl border border-border bg-muted/30 p-3"><div><p className="text-sm font-medium">{asset.name}</p><p className="mt-1 text-xs text-muted-foreground">{asset.mediaType} · {(asset.sizeBytes / 1024).toFixed(1)} KB · {asset.status}</p></div><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={downloadUrl.isPending} onClick={() => workspaceId && downloadUrl.mutate({ workspaceId, assetId: asset.id })}>Open</Button><span className="rounded-full bg-[#e4eee6] px-2.5 py-1 text-xs font-medium text-[#405c4c]">v{asset.currentVersionNumber}</span></div></div>)}{!assets.isLoading && assets.data?.length === 0 ? <p className="rounded-2xl border border-dashed p-6 text-center text-sm text-muted-foreground">No project assets yet. Upload the first governed working asset.</p> : null}</CardContent></Card></section>
      <section className="grid gap-5 lg:grid-cols-2"><Card className="border-border bg-white"><CardHeader><CardTitle>Review and approval</CardTitle><CardDescription>Request decisions from workspace members and record the response against this project.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-[1fr_0.75fr_auto]"><Input value={reviewNote} onChange={event => setReviewNote(event.target.value)} placeholder="What needs review?" /><select aria-label="Assigned reviewer" className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={reviewerUserId ?? ""} onChange={event => setReviewerUserId(event.target.value ? Number(event.target.value) : undefined)}><option value="">Any eligible member</option>{members.data?.map(member => <option key={member.userId} value={member.userId}>{member.name || member.email || `User #${member.userId}`} · {member.role}</option>)}</select><Button disabled={!workspaceId || !projectId || requestReview.isPending} onClick={() => workspaceId && projectId && requestReview.mutate({ workspaceId, projectId, requestNote: reviewNote || undefined, reviewerUserId })} className="bg-[#516f5e] hover:bg-[#405c4c]"><Send className="mr-1 h-4 w-4" />Request</Button></div>{reviews.isLoading ? <p className="text-sm text-muted-foreground">Loading review records…</p> : null}{reviews.data?.map(review => <article key={review.id} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{review.requestNote || "Review requested"}</p><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium text-muted-foreground">{review.status.replace("_", " ")}</span></div>{review.status === "pending" ? <div className="mt-3 flex gap-2"><Button size="sm" variant="outline" disabled={respond.isPending} onClick={() => workspaceId && respond.mutate({ workspaceId, reviewId: review.id, status: "changes_requested" })}><ThumbsDown className="mr-1 h-3.5 w-3.5" />Changes</Button><Button size="sm" disabled={respond.isPending} onClick={() => workspaceId && respond.mutate({ workspaceId, reviewId: review.id, status: "approved" })} className="bg-[#516f5e] hover:bg-[#405c4c]"><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Approve</Button></div> : null}</article>)}{reviews.data?.length === 0 ? <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">No review requests have been created for this project.</p> : null}</CardContent></Card>
        <Card className="border-border bg-white"><CardHeader><CardTitle>Delivery preparation</CardTitle><CardDescription>Prepare a traceable delivery record before a provider-neutral handoff.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-[0.7fr_1.3fr_auto]"><select aria-label="Delivery destination type" className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={destinationType} onChange={event => setDestinationType(event.target.value)}><option value="secure_link">Secure link</option><option value="client_portal">Client portal</option><option value="provider_handoff">Provider handoff</option></select><Input value={destinationRef} onChange={event => setDestinationRef(event.target.value)} placeholder="Optional destination reference" /><Button disabled={!workspaceId || !projectId || createDelivery.isPending} onClick={() => workspaceId && projectId && createDelivery.mutate({ workspaceId, projectId, destinationType, destinationRef: destinationRef || undefined })} className="bg-[#17202b] hover:bg-[#2a3746]">Create</Button></div>{deliveries.isLoading ? <p className="text-sm text-muted-foreground">Loading delivery records…</p> : null}{deliveries.data?.map(delivery => <article key={delivery.id} className="flex items-center justify-between gap-3 rounded-xl border border-border p-4"><div><p className="text-sm font-medium capitalize">{delivery.destinationType.replace("_", " ")}</p><p className="mt-1 text-xs text-muted-foreground">{delivery.destinationRef || "No external reference"} · {delivery.status}</p></div>{delivery.status === "draft" ? <Button size="sm" disabled={readyDelivery.isPending} onClick={() => workspaceId && readyDelivery.mutate({ workspaceId, deliveryId: delivery.id })} className="bg-[#516f5e] hover:bg-[#405c4c]"><PackageCheck className="mr-1 h-3.5 w-3.5" />Ready</Button> : <span className="rounded-full bg-[#e4eee6] px-2.5 py-1 text-xs font-medium text-[#405c4c]">{delivery.status}</span>}</article>)}{deliveries.data?.length === 0 ? <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">No delivery records exist yet.</p> : null}</CardContent></Card></section>
      {workspaceId && projectId ? <StudioAssetVersionHistory workspaceId={workspaceId} projectId={projectId} /> : null}
      {workspaceId && projectId ? <StudioPublishingHandoff workspaceId={workspaceId} projectId={projectId} /> : null}
    </> : <Card className="border-dashed"><CardContent className="p-8 text-center text-sm text-muted-foreground">Select or create a Studio project to begin the governed workflow.</CardContent></Card>}
  </div></DashboardLayout>;
}
