import { Button } from "@/components/ui/button";
import { ArrowRight, LockKeyhole, Sparkles } from "lucide-react";
import { Link, useLocation } from "wouter";

const pathway = [
  ["01", "Memory", "You share the memory once, privately, in your own words."],
  ["02", "Essence", "You recognize or correct the emotional center before anything moves forward."],
  ["03", "Story", "Evercrafted deepens meaning without inventing biography, materials, or construction."],
  ["04", "Florals", "You choose a small, source-versioned reference set by role and save it in My Wreath Tray—without an inventory or purchase claim."],
  ["05", "Recipe", "Your four role choices become an immutable, passing reference snapshot. It has no quantity, inventory, price, or construction claim."],
  ["06", "Blueprint", "A deterministic simplified hierarchy reads the locked Recipe without adding flowers, geometry, or production instructions."],
  ["07", "Render package", "You review and approve a source-bound package with a renderer rule and explicit exclusions. A manual handoff records intent only; it does not call a provider or create an image."],
  ["08", "Outcome", "Commission, purchase, Lookbook, and publication remain gated until their own verified data, policy, and approval conditions exist."],
] as const;

export default function WreathPublic() {
  const [location] = useLocation();
  const mode = location.startsWith("/signature-wreaths") ? "signature" : location.startsWith("/moodoor") ? "moodoor" : location.startsWith("/pricing") ? "pricing" : "how";
  const content = {
    how: { eyebrow: "How Evercrafted works", title: "A wreath does not begin with a product. It begins with what you remember.", body: "Evercrafted preserves the distinction between your original memory, the meaning you recognize in it, and the material decisions that follow. You remain part of every approval, including the current render-package review before any future provider workflow." },
    signature: { eyebrow: "Signature Wreath Collection", title: "Objects of meaning, ready to meet another memory.", body: "The Signature Wreath Collection will present published designs with their approved Essence, Story, and material context. Personalization begins a new private Memory Thread; it never rewrites a published story." },
    moodoor: { eyebrow: "Moodoor Studio", title: "The workbench behind a design that can be traced.", body: "Moodoor is the creator and operator pathway for approved render upload, analysis, package creation, provenance, and publication review. The dedicated upload workflow follows the Guided Journey Shell review so the shared source and approval rules are in place first." },
    pricing: { eyebrow: "Pricing and access", title: "Clear options only when the underlying work is ready to stand behind them.", body: "Evercrafted will publish product and commission pricing only from verified catalog, availability, and provider data. Until then, this page does not imply prices, inventory, reservations, subscriptions, or checkout availability that have not been configured." },
  }[mode];
  return <main className="min-h-screen bg-[#F6F3EE] px-5 py-7 text-[#23211F] sm:px-8"><nav className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="font-editorial text-2xl tracking-[-.04em]">Evercrafted</Link><div className="hidden gap-6 text-sm text-[#5E564E] md:flex"><Link href="/create">Create from a memory</Link><Link href="/signature-wreaths">Signature Wreaths</Link><Link href="/moodoor">Moodoor</Link><Link href="/how-it-works">How it works</Link></div><Link href="/create" className="rounded-full bg-[#23211F] px-4 py-2 text-sm text-white">Begin privately</Link></nav><section className="mx-auto max-w-7xl py-16 sm:py-24"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#6B5A4A]">{content.eyebrow}</p><h1 className="mt-5 max-w-4xl font-editorial text-5xl leading-[.94] tracking-[-.055em] sm:text-7xl">{content.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5E564E]">{content.body}</p>{mode === "how" ? <div className="mt-12 grid gap-px overflow-hidden rounded-[2rem] border border-[#DCD4C9] bg-[#DCD4C9] md:grid-cols-2 xl:grid-cols-4">{pathway.map(([number, title, body]) => <article key={title} className="bg-[#FFFEFB] p-6"><span className="text-xs text-[#6B5A4A]">{number}</span><h2 className="mt-10 font-editorial text-3xl">{title}</h2><p className="mt-4 text-sm leading-6 text-[#5E564E]">{body}</p></article>)}</div> : <div className="mt-12 rounded-[2rem] border border-[#DCD4C9] bg-[#FFFEFB] p-7 sm:p-10"><div className="flex max-w-2xl items-start gap-4"><LockKeyhole className="mt-1 h-5 w-5 shrink-0 text-[#50645B]" /><div><h2 className="font-editorial text-3xl">An intentional boundary, not a placeholder promise.</h2><p className="mt-4 text-base leading-7 text-[#5E564E]">{mode === "moodoor" ? "Moodoor’s real workflow is render → upload → analyze → package → publish. It will remain distinct from customer guidance and will only be exposed when its secure upload, provenance, and publication review paths are restored." : "This route is visible so the product map is clear. It becomes transactional or publishable only when its real data, policy, and approval conditions exist."}</p></div></div></div>}<div className="mt-12 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-full bg-[#23211F] px-6 text-white hover:bg-[#50645B]"><Link href="/create">Create from a memory <ArrowRight className="ml-2 h-4 w-4" /></Link></Button>{mode !== "how" ? <Button asChild variant="outline" className="h-12 rounded-full border-[#BEB3A4] bg-transparent px-6"><Link href="/how-it-works">See the journey</Link></Button> : null}</div></section></main>;
}
